### ISSUE TITLE
Definir Textos de Home page

### ISSUE THREAD

**Issue by elmasse** [laplatajs/laplatajs.github.io#1]
Hay que definir un poco que vamos a poner en las dos secciones de la home:

Quiero Participar

Quiero Ayudar

**Comment by elmasse** [comment]
Bueno esto es lo que tengo por ahora::

Quiero Participar:
Hay varias formas de participar. Recordá que la meetup es tuya. Si estas interesado en dar una charla, te gustaria proponer un tema o tal vez estas interesado en charlar con otros miembros de la comunidad solo tenes que ponerte en contacto con nosotros.

Quiero Ayudar:
Hay muchas maneras de ayudar a hacer que la comunidad crezca. Si tenes una empresa y estas interesado en patrocinar una de las charlas es mas que bienvenido! Hacemos todo a pulmon! Tratamos de conseguir los espacios fisicos y gente que quiera colaborar para poder ofrecer algun refrigerio. Todo aporte es bienvenido. No dudes en contactarnos.

**Comment by dpaez** [comment]
Un poco de edición:

---

Quiero Participar:
Hay varias formas de participar. Recordá que la meetup es tuya. Si estas interesado en dar una charla, te gustaría proponer un tema o simplemente queres conocer a otros miembros de la comunidad, solo tenes que ponerte en contacto.

Quiero Ayudar:
Hay muchas maneras de ayudar a hacer que la comunidad crezca. Si tenes una empresa y estas interesado en patrocinar una de las charlas eso es mas que bienvenido! Hacemos todo a pulmón! Tratamos de conseguir los espacios físicos y gente que quiera colaborar para poder ofrecer algún refrigerio. Todo aporte suma. No dudes en escribirnos.

**Comment by elmasse** [comment]
Quedo en prod la primer version del rediseño. Cerramos este issue y vamos viendo los ajustes.
